define({
    'groups' : 'Groupe',
    'domains' : 'Domaine',
    'subdomains' : 'Sub-Domaine',
    'areas' : 'Zone Geographique',
    'items' : 'Articles',
    'item' : 'Article',
    'elements' : 'Elements',
    'ghg': 'Gaz a Effet de Serre',
    'ghg_overview': 'Aperçu Regional',
    'ghg_quality': 'AQ-CQ et Verification',
    'ghg_indicators': 'Indicateurs',
    'ghg_data': 'Donnees Georeferencees',
    'please_select': 's\'il vous plait selectionnez...',
    'verification': 'Comparison',
    'qa_qc': 'AQ/CQ',
    'gt': 'Agriculture total',
    'ge': 'Fermentation entérique',
    'gm': 'Gestion du fumier',
    'gr': 'Riziculture',
    'gy': 'Engrais synthétique',
    'gu': 'Fumier appliquée aux sols',
    'gp': 'Fumier déposée sur des pâturages',
    'ga': 'Résidus de récoltes',
    'gv': 'Culture de sols organiques',
    'gb': 'Combustion - résidus de récoltes',
    'gh': 'Combustion - Savane',
    'gn': 'Consommation d\'énergie',
    'gl': 'Utilisation des terres total',
    'gf': 'Terres forestières',
    'gc': 'Terres cultivées',
    'gg': 'Prairie',
    'gi': 'Combustion - Biomasse',
    'ag_soils': 'Agricultural Soils',
    'charts': 'Graphiques',
    'tables': 'Tables',
    'emissions': 'Emissions',
    'emissions_activity': 'Emissions Activity',
    'emissions_factor': 'Emissions Factor',
    'data_not_available': 'Données Non Disponibles',
    'faostat': 'FAOSTAT',
    'nc': 'Communication Nationale',
    'difference': 'Difference',
    'norm_difference': 'Normalized Difference',
    'ghg_description': 'Description',
    'ghg_overview_description': 'Aperçu Regional description.',
    'ghg_quality_description': 'AQ-CQ et Verification description.',
    'ghg_indicators_description': 'Indicateurs description.',
    'ghg_data_description': 'Donnees Georeferencees description.',
    'ghg_button': 'Aller vers le module de gaz à effet de serre.',
    'ghg_overview_button': 'Aller vers le module de Aperçu Regional.',
    'ghg_quality_button': 'Aller vers le module de AQ-CQ et Verification.',
    'ghg_indicators_button': 'Aller vers le module de Indicateurs.',
    'ghg_data_button': 'Aller vers le module de Donnees Georeferencees.',
    'analysis': 'Analyse'
});