define({
    'root' : {
        'groups' : 'Groups',
        'domains' : 'Domains',
        'subdomains' : 'Sub-Domains',
        'areas' : 'Geographic Areas',
        'items' : 'Items',
        'item' : 'Item',
        'elements' : 'Elements',
        'ghg': 'Greenhouse Gases',
        'ghg_overview': 'Regional Overview',
        'ghg_quality': 'QA-QC and Verification',
        'ghg_indicators': 'Indicators',
        'ghg_data': 'Georeferenced Data',
        'please_select': 'Please Select...',
        'verification': 'Comparison',
        'qa_qc': 'QA/QC',
        'gt': 'Agriculture Total',
        'ge': 'Enteric Fermentation',
        'gm': 'Manure Management',
        'gr': 'Rice Cultivation',
        'gy': 'Synthetic Fertilizers',
        'gu': 'Manure applied to Soils',
        'gp': 'Manure left on Pasture',
        'ga': 'Crop Residues',
        'gv': 'Cultivation of Organic Soils',
        'gb': 'Burning - Crop Residues',
        'gh': 'Burning - Savanna',
        'gn': 'Energy Use',
        'gl': 'Land Use Total',
        'gf': 'Forest Land',
        'gc': 'Cropland',
        'gg': 'Grassland',
        'gi': 'Burning - Biomass',
        'ag_soils': 'Agricultural Soils',
        'charts': 'Charts',
        'tables': 'Tables',
        'emissions': 'Emissions',
        'emissions_activity': 'Activity data',
        'emissions_factor': 'Emission factor',
        'data_not_available': 'Data Not Available',
        'faostat': 'FAOSTAT',
        'nc': 'National Communication',
        'difference': 'Difference',
        'norm_difference': 'Normalized Difference',
        'ghg_description': 'Description',
        'ghg_overview_description': 'Regional Overview module description.',
        'ghg_quality_description': 'QA-QC and Verification module description.',
        'ghg_indicators_description': 'Indicators module description.',
        'ghg_data_description': 'Georeferenced Data module description.',
        'ghg_button': 'Go to the Greenhouse Gases module.',
        'ghg_overview_button': 'Go to the Regional Overview module.',
        'ghg_quality_button': 'Go to the QA-QC and Verification module.',
        'ghg_indicators_button': 'Go to the Indicators module.',
        'ghg_data_button': 'Go to the Georeferenced Data module.',
        'analysis': 'Analysis'
    },
    'F' : true,
    'S' : true
});