define({
    'company' : 'Casa',
    'browse': 'Esplora',
    'download': 'Scarica',
    'scheduler': 'Pianificatore',
    'configuration': 'Configurazione',
    'login': 'Autenticazione',
    'data_providers': 'Sorgenti Dati',
    'please_select': 'Selezionare Prego...',
    'download_label': 'Scarica Layer Selezionati',
    'selectors_label': 'Selettori',
    'progress_label': 'Progresso',
    'countries': 'Paesi',
    'jan': 'Gennaio',
    'feb': 'Febbraio',
    'mar': 'Marzo',
    'apr': 'Aprile',
    'may': 'Maggio',
    'jun': 'Giugno',
    'jul': 'Luglio',
    'aug': 'Agosto',
    'sep': 'Settembre',
    'oct': 'Ottobre',
    'nov': 'Novembre',
    'dec': 'Dicembre'
});