define({
    'groups' : 'Groupe',
    'domains' : 'Domaine',
    'subdomains' : 'Sub-Domaine',
    'areas' : 'Zone Geographique',
    'items' : 'Articles',
    'elements' : 'Elements',
    'ghg': 'Gaz a Effet de Serre',
    'ghg_overview': 'Aperçu Regional',
    'ghg_quality': 'AQ-CQ et Verification',
    'ghg_indicators': 'Indicateurs',
    'ghg_data': 'Donnees Georeferencees',
    'please_select': 's\'il vous plait selectionnez...',
    'verification': 'Vérification',
    'qa_qc': 'AQ/CQ',
    'gt': 'Agriculture total',
    'ge': 'Fermentation entérique',
    'gm': 'Gestion du fumier',
    'gr': 'Riziculture',
    'gy': 'Engrais synthétique',
    'gu': 'Fumier appliquée aux sols',
    'gp': 'Fumier déposée sur des pâturages',
    'ga': 'Résidus de récoltes',
    'gv': 'Culture de sols organiques',
    'gb': 'Combustion - résidus de récoltes',
    'gh': 'Combustion - Savane',
    'gn': 'Consommation d\'énergie',
    'gl': 'Utilisation des terres total',
    'gf': 'Terres forestières',
    'gc': 'Terres cultivées',
    'gg': 'Prairie',
    'gi': 'Combustion - Biomasse'
});