define({
    'groups' : 'Groupe',
    'domains' : 'Domaine',
    'subdomains' : 'Sub-Domaine',
    'areas' : 'Zone Geographique',
    'items' : 'Articles',
    'item' : 'Article',
    'elements' : 'Elements',
    'ghg': 'Gaz a Effet de Serre',
    'ghg_overview': 'Aperçu Regional',
    'ghg_quality': 'AQ-CQ et Verification',
    'ghg_indicators': 'Indicateurs',
    'ghg_data': 'Donnees Georeferencees',
    'please_select': 's\'il vous plait selectionnez...',
    'verification': 'Verification',
    'qa_qc': 'AQ/CQ',
    'gt': 'Agriculture total',
    'ge': 'Fermentation entérique',
    'gm': 'Gestion du fumier',
    'gr': 'Riziculture',
    'gy': 'Engrais synthétique',
    'gu': 'Fumier appliquée aux sols',
    'gp': 'Fumier déposée sur des pâturages',
    'ga': 'Résidus de récoltes',
    'gv': 'Culture de sols organiques',
    'gb': 'Combustion - résidus de récoltes',
    'gh': 'Combustion - Savane',
    'gn': 'Consommation d\'énergie',
    'gl': 'Utilisation des terres total',
    'gf': 'Terres forestières',
    'gc': 'Terres cultivées',
    'gg': 'Prairie',
    'gi': 'Combustion - Biomasse',
    'ag_soils': 'Sols agricoles',
    'charts': 'Graphiques',
    'tables': 'Tables',
    'emissions': 'Emissions (Gg CO2eq)',
    'emissions_activity': 'Emissions Activité',
    'emissions_factor': 'Implicite Facteur d\'émission (unités)',
    'data_not_available': 'Données Non Disponibles',
    'faostat': 'FAOSTAT',
    'nc': 'Communication Nationale',
    'difference': 'Différence (Communication Nationale - FAOSTAT)',
    'norm_difference': 'Différence Normalisée (Communication Nationale - FAOSTAT)',
    'code': 'Code',
    'category': 'Catégorie',
    'agriculture': 'Agriculture',
    'direct_soil_emissions': 'Émissions directes des sols',
    'pasture_paddock_maure': 'Fumier déposé sur des pâturages/parcours/parcelles',
    'indirect_emissions': 'Émissions indirectes',
    'co2eq': '(Emissions Gg CO2eq)',
    'export_data_label': 'Exporter des Données'
});