define({
    'country': 'Pays',
    'fromyear': 'D&#180;Annee',
    'toyear': 'A l&#180;Annee',
    'world': 'Monde',
    'continents': 'Continents',
    'regions': 'Regiones',
    'agriculture_total': 'Agriculture Total',
    'countries': 'Pays',
    'sector': 'Secteur',
    'show_hide_table_breakdown': 'Afficher/Masquer la table Ventilation',
    'country_region': 'Pays/R&eacute;gions',
    'enteric_fermentation': 'Fermentation ent&eacute;rique',
    'sum_of_countries': 'Somme des Pays',
    'manure_management': 'Gestion du fumier',
    'agricultural_soils': 'Culture de sols organiques',
    'rice_cultivation': 'Riziculture',
    'burning_crops_residues': 'Combustion - r&eacute;sidus de r&eacute;coltes',
    'burning_savanna': 'Combustion - Savane',
    'ghg_overview_title': 'Aperçu r&eacute;gional des &eacute;missions',
    'ghg_overview_note': "Sélectionnez un (des) pays et d’autres détails ci-dessus. L'outil fournira une série de résultats au format graphique et tabulaire. Lors de la sélection de deux ou plusieurs pays, l'information sera présentée comme une somme.",
    'ghg_overview_subnote': "Pour plus d'informations, un guide de l'utilisateur est disponible ici.",
    'agriculture': 'Agriculture',
    'land_use': 'Land Use',
    'by_continent': 'Par Continent',
    'category': 'Cat&eacute;gorie',
    'no_data_to_display': 'No data to display',
    'grand_total':'Total',
    'select_one_or_more_countries': 'Sélectionnez un ou plusieurs pays',
    'by_country': 'Par Pays',
    'continent': 'Continent',
    'region': 'R&eacute;gion',
    'total': 'Total',
    'pie_mu': 'Gg CO2eq'
});