define({
    'country': 'País',
    'fromyear': 'Desde el Año',
    'toyear': 'Hasta el año',
    'world': 'Mundo',
    'continents': 'Continentes',
    'regions': 'Regiones',
    'agriculture_total': 'Agricultura Total',
    'countries': 'Paises',
    'sector': 'Sector',
    'show_hide_table_breakdown': 'Mostrar/Ocultar tablas',
    'country_region': 'Países/Regiones',
    'enteric_fermentation': 'Fermentación entérica',
    'sum_of_countries': 'Suma de los Países',
    'manure_management': 'Gestión del estiércol',
    'agricultural_soils': 'Cultivación de suelos orgánicos',
    'rice_cultivation': 'Cultivo del arroz',
    'burning_crops_residues': 'Quemado de residuos agrícolas',
    'burning_savanna': 'Quemado de sabana',
    'ghg_overview_title': 'Panorama de las emisiones',
    'ghg_overview_note': 'Seleccione el/los país(es) y los otros detalles correspondientes arriba. La herramienta mostrará una serie de',
    'ghg_overview_subnote': 'Para obtener más información, una guía del usuario está disponible aquí.',
    'agriculture': 'Agricultura',
    'land_use': 'Land Use',
    'by_continent': 'Por Continente',
    'category': 'Categoría',
    'no_data_to_display': 'No data to display',
    'grand_total':'Gran Total',
    'select_one_or_more_countries': 'Seleccionar uno o más países',
    'by_country': 'Por País',
    'continent': 'Continente',
    'region': 'Región',
    'total': 'Total',
    'pie_mu': 'Gg CO2eq'
});