define({
    'groups' : 'Grupos',
    'domains' : 'Dominios',
    'subdomains' : 'Sub-Dominios',
    'areas' : 'Areas',
    'items' : 'Articulos',
    'item' : 'Articulo',
    'elements' : 'Elementos',
    'ghg': 'Gases de Efecto Invernadero',
    'ghg_overview': 'Panorama Regional',
    'ghg_quality': 'GC-CC y Verificacion',
    'ghg_indicators': 'Indicadores',
    'ghg_data': 'Datos Georreferenciados',
    'please_select': 'Por Favor Seleccione...',
    'verification': 'Comparison',
    'qa_qc': 'SG/CQ',
    'gt': 'Agricultura total',
    'ge': 'Fermentación entérica',
    'gm': 'Gestión del estiércol',
    'gr': 'Cultivo del arroz',
    'gy': 'Fertilizantes sintéticos',
    'gu': 'Estiércol aplicado a los suelos',
    'gp': 'Estiércol depositado en las pasturas',
    'ga': 'Residuos agrícolas',
    'gv': 'Cultivación de suelos orgánicos',
    'gb': 'Combustión - residuos agrícolas',
    'gh': 'Combustión - Sabana',
    'gn': 'Use de energía',
    'gl': 'Uso de la tierra total',
    'gf': 'Tierras forestales',
    'gc': 'Tierras de cultivo',
    'gg': 'Pastizales',
    'gi': 'Combustión de biomasa',
    'ag_soils': 'Agricultural Soils',
    'charts': 'Gráficos',
    'tables': 'Tablas',
    'emissions': 'Emisiones',
    'emissions_activity': 'Dato de actividad',
    'emissions_factor': 'Factor de emisión',
    'data_not_available': 'Datos No Disponible',
    'faostat': 'FAOSTAT',
    'nc': 'Comunicación Nacional',
    'difference': 'Diferencia',
    'norm_difference': 'Diferencia normalizada '
});