define({
    'groups' : 'Grupos',
    'domains' : 'Dominios',
    'subdomains' : 'Sub-Dominios',
    'areas' : 'Areas',
    'items' : 'Articulos',
    'elements' : 'Elementos',
    'ghg': 'Gases de Efecto Invernadero',
    'ghg_overview': 'Panorama Regional',
    'ghg_quality': 'GC-CC y Verificacion',
    'ghg_indicators': 'Indicadores',
    'ghg_data': 'Datos Georreferenciados',
    'please_select': 'Por Favor Seleccione...',
    'verification': 'Verificación',
    'qa_qc': 'SG/CQ',
    'gt': 'Agricultura total',
    'ge': 'Fermentación entérica',
    'gm': 'Gestión del estiércol',
    'gr': 'Cultivo del arroz',
    'gy': 'Fertilizantes sintéticos',
    'gu': 'Estiércol aplicado a los suelos',
    'gp': 'Estiércol depositado en las pasturas',
    'ga': 'Residuos agrícolas',
    'gv': 'Cultivación de suelos orgánicos',
    'gb': 'Combustión - residuos agrícolas',
    'gh': 'Combustión - Sabana',
    'gn': 'Use de energía',
    'gl': 'Uso de la tierra total',
    'gf': 'Tierras forestales',
    'gc': 'Tierras de cultivo',
    'gg': 'Pastizales',
    'gi': 'Combustión de biomasa'
});