define({
    'company' : 'Casa',
    'browse': 'Explorar',
    'download': 'Baixar',
    'scheduler': 'Organizador',
    'configuration': 'Configuração',
    'login': 'Autenticar',
    'data_providers': 'Provedores de Dados',
    'please_select': 'Selecione Por Favor...',
    'download_label': 'Baixar Layer Selecionados',
    'selectors_label': 'Seletores',
    'progress_label': 'Avanço',
    'countries': 'Países',
    'jan': 'Janeiro',
    'feb': 'Fevereiro',
    'mar': 'Março',
    'apr': 'Abril',
    'may': 'Maio',
    'jun': 'Junho',
    'jul': 'Julho',
    'aug': 'Agosto',
    'sep': 'Setembro',
    'oct': 'Outubro',
    'nov': 'Novembro',
    'dec': 'Dezembro'
});