define({
    'root' : {
        'groups' : 'Groups',
        'domains' : 'Domains',
        'subdomains' : 'Sub-Domains',
        'areas' : 'Geographic Areas',
        'items' : 'Items',
        'elements' : 'Elements',
        'ghg': 'Greenhouse Gases',
        'ghg_overview': 'Regional Overview',
        'ghg_quality': 'QA-QC and Verification',
        'ghg_indicators': 'Indicators',
        'ghg_data': 'Georeferenced Data',
        'please_select': 'Please Select...',
        'verification': 'Verification',
        'qa_qc': 'QA/QC',
        'gt': 'Agriculture Total',
        'ge': 'Enteric Fermentation',
        'gm': 'Manure Management',
        'gr': 'Rice Cultivation',
        'gy': 'Synthetic Fertilizers',
        'gu': 'Manure applied to Soils',
        'gp': 'Manure left on Pasture',
        'ga': 'Crop Residues',
        'gv': 'Cultivation of Organic Soils',
        'gb': 'Burning - Crop Residues',
        'gh': 'Burning - Savanna',
        'gn': 'Energy Use'
    },
    'F' : true,
    'S' : true
});