define({
    'root' : {
        'company' : 'Home',
        'browse': 'Browse',
        'download': 'Download',
        'scheduler': 'Scheduler',
        'configuration': 'Configuration',
        'login': 'Login',
        'data_providers': 'Data Providers',
        'please_select': 'Please Select...',
        'download_label': 'Download Selected Layers',
        'selectors_label': 'Selectors',
        'progress_label': 'Progress',
        'countries': 'Countries',
        'jan': 'January',
        'feb': 'February',
        'mar': 'March',
        'apr': 'April',
        'may': 'May',
        'jun': 'June',
        'jul': 'July',
        'aug': 'August',
        'sep': 'September',
        'oct': 'October',
        'nov': 'November',
        'dec': 'December'
    },
    'it' : true,
    'pt' : true
});