define({
    'root' : {
        'country': 'Country',
        'fromyear': 'From Year',
        'toyear': 'To Year',
        'world': 'World',
        'continents': 'Continents',
        'regions': 'Regions',
        'agriculture_total': 'Agriculture Total',
        'countries': 'Countries',
        'sector': 'Sector',
        'show_hide_table_breakdown': 'Show/Hide Table Breakdown',
        'country_region': 'Country / Region',
        'enteric_fermentation': 'Enteric Fermentation',
        'sum_of_countries': 'Sum of countries',
        'manure_management': 'Manure Management',
        'agricultural_soils': 'Agricultural Soils',
        'rice_cultivation': 'Rice Cultivation',
        'burning_crops_residues': 'Burning  Crops Residues',
        'burning_savanna': 'Burning  Savanna',
        'ghg_overview_title': 'Regional overview of the emissions',
        'ghg_overview_note': 'Start by selecting the country(ies) and other relevant details above. <br> The tool will return a series of results in graphical and tabular format. <br>When selecting two or more countries, the information will be presented as a sum.<br>For more information, a user instruction guide is available here.',
        'ghg_overview_subnote': 'For more information, a user instruction guide is available here.',
        'agriculture': 'Agriculture',
        'land_use': 'Land Use',
        'by_continent': 'By Continent',
        'category': 'Category',
        'no_data_to_display': 'No data to display',
        'grand_total':'Grand Total',
        'select_one_or_more_countries':'Select one or more countries',
        'by_country': 'By Country',
        'continent': 'Continent',
        'region': 'Region',
        'total': 'Total',
        'pie_mu': 'Gg CO2eq'
    },
    'F' : true,
    'S' : true
});