define({
    'root' : {
        'groups' : 'Groups',
        'domains' : 'Domains',
        'subdomains' : 'Sub-Domains',
        'areas' : 'Geographic Areas',
        'items' : 'Items',
        'item' : 'Item',
        'elements' : 'Elements',
        'ghg': 'Greenhouse Gases',
        'ghg_overview': 'Regional Overview',
        'ghg_quality': 'QA-QC and Verification',
        'ghg_indicators': 'Indicators',
        'ghg_data': 'Georeferenced Data',
        'please_select': 'Please Select...',
        'verification': 'Verification',
        'qa_qc': 'QA/QC',
        'gt': 'Agriculture Total',
        'ge': 'Enteric Fermentation',
        'gm': 'Manure Management',
        'gr': 'Rice Cultivation',
        'gy': 'Synthetic Fertilizers',
        'gu': 'Manure applied to Soils',
        'gp': 'Manure left on Pasture',
        'ga': 'Crop Residues',
        'gv': 'Cultivation of Organic Soils',
        'gb': 'Burning - Crop Residues',
        'gh': 'Burning - Savanna',
        'gn': 'Energy Use',
        'gl': 'Land Use Total',
        'gf': 'Forest Land',
        'gc': 'Cropland',
        'gg': 'Grassland',
        'gi': 'Burning - Biomass',
        'ag_soils': 'Agricultural Soils',
        'charts': 'Charts',
        'tables': 'Tables',
        'emissions': 'Emissions (Gg CO2eq)',
        'emissions_activity': 'Activity data',
        'emissions_factor': 'Implied Emission Factor (Units)',
        'data_not_available': 'Data Not Available',
        'faostat': 'FAOSTAT',
        'nc': 'National Communication',
        'difference': 'Difference (National Communication - FAOSTAT)',
        'norm_difference': 'Normalized Difference (National Communication - FAOSTAT)',
        'code': 'Code',
        'category': 'Category',
        'agriculture': 'Agriculture',
        'direct_soil_emissions': 'Direct Soil Emissions',
        'pasture_paddock_maure': 'Pasture, Range and Paddock Manure',
        'indirect_emissions': 'Indirect Emissions',
        'co2eq': '(Emissions Gg CO2eq)',
        'table_selector_label': 'Table Selector',
        'export_data_label': 'Export Data'
    },
    'F' : true,
    'S' : true
});